# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GymBros' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  #API Handling
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'

  # Pods for GymBros
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

end
